### ISSUE TITLE
[Server] ERROR Could not load 'plugins/ProtectingWolf.jar' in folder 'plugins'

### ISSUE THREAD

**Issue by Petoovee** [h4rvk4/ProtectingWolf#1]
22.10 16:22:58 [Multicraft] Skipped 43 lines due to rate limit (30/s)
22.10 16:22:56 [Server] INFO at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_60]
22.10 16:22:56 [Server] INFO at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_60]
22.10 16:22:56 [Server] INFO at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_60]
22.10 16:22:56 [Server] INFO at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_60]
22.10 16:22:56 [Server] INFO at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.8.0_60]
22.10 16:22:56 [Server] INFO at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.8.0_60]
22.10 16:22:56 [Server] INFO at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_60]
22.10 16:22:56 [Server] INFO at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_60]
22.10 16:22:56 [Server] INFO at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_60]
22.10 16:22:56 [Server] INFO Caused by: java.lang.NoClassDefFoundError: org/bukkit/event/entity/EntityListener
22.10 16:22:56 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.8.0_60]
22.10 16:22:56 [Server] INFO at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:503) [craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-880a532]
22.10 16:22:56 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:179) [craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-880a532]
22.10 16:22:56 [Server] INFO at net.minecraft.server.v1_8_R3.DedicatedPlayerList.<init>(SourceFile:14) [craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-880a532]
22.10 16:22:56 [Server] INFO at net.minecraft.server.v1_8_R3.PlayerList.<init>(PlayerList.java:69) [craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-880a532]
22.10 16:22:56 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.<init>(CraftServer.java:251) [craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-880a532]
22.10 16:22:56 [Server] INFO at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:289) [craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-880a532]
22.10 16:22:56 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:251) [craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-880a532]
22.10 16:22:56 [Server] INFO at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:328) ~[craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-880a532]
22.10 16:22:56 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[craftbukkit-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Bukkit-880a532]
22.10 16:22:56 [Server] INFO org.bukkit.plugin.InvalidPluginException: java.lang.NoClassDefFoundError: org/bukkit/event/entity/EntityListener

**Comment by Petoovee** [comment]
Sorry for the wall of text, havn't learned this "Styling with Markdown" thing yet.

**Comment by h4rvk4** [comment]
Sorry for the late answer. I thought long about your issue. But I'll not go to fix it.

Because ProtectingWolf was made for craftbukkit 1.7.*. If it would accidentally run with 1.8, okay. But it doesn't seem so and since the takedown, there is no official(!) build of craftbukkit for 1.8, so I'm not going to support it. Sorry for that, too.

But ProtectingWolf is open source... feel free to fork it! :smile:
